name: Site workflow

on:
  push:
    branches: [ main ]


jobs:
  updatesite:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: copy
       run: |
        echo 'CONTENT_ENV<<EOF' >> $GITHUB_ENV
        cat README.md >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
     - name: checkout site branch
       uses: actions/checkout@v2
       with:
        ref: 'gh-pages'
     - name: paste
       run: echo "$CONTENT_ENV" > index.md
     - name: commit
       uses: stefanzweifel/git-auto-commit-action@v4
       with:
        commit_message: Automatic update ${{ github.run_number }}
     - name: push
       run: git push 
